import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { PlanCard } from '../components/PlanCard';
import { CardSkeleton } from '../components/Loader';
import { Brain, Compass, MessageCircle, Sparkles, BookOpen, GraduationCap, ChevronDown, Award, Send, Users, TrendingUp, HelpCircle } from 'lucide-react';
import confetti from 'canvas-confetti';

export const Home: React.FC = () => {
  const [plans, setPlans] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [seeding, setSeeding] = useState(false);
  const [newsletterEmail, setNewsletterEmail] = useState('');
  const [newsletterSubscribed, setNewsletterSubscribed] = useState(false);

  // Accordion active state
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  useEffect(() => {
    fetchPlans();
  }, []);

  const fetchPlans = async () => {
    setLoading(true);
    try {
      const data = await api.getPlans();
      if (data.success && data.plans && data.plans.length > 0) {
        setPlans(data.plans.slice(0, 4));
      } else {
        // Auto-seed database if empty to guarantee beautiful populated landing page
        setSeeding(true);
        const seedResult = await api.seedDatabase();
        if (seedResult.success) {
          const freshData = await api.getPlans();
          if (freshData.success) {
            setPlans(freshData.plans.slice(0, 4));
          }
        }
        setSeeding(false);
      }
    } catch (err) {
      console.error('Error fetching landing plans:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubscribe = (e: React.FormEvent) => {
    e.preventDefault();
    if (newsletterEmail) {
      setNewsletterSubscribed(true);
      setNewsletterEmail('');
      confetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.8 }
      });
    }
  };

  const toggleFaq = (index: number) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const faqData = [
    {
      q: "What is StudyForge AI and how does it work?",
      a: "StudyForge AI is an advanced planning platform. You supply a learning subject, difficulty level, and study hours. Our system queries Gemini LLMs to assemble a week-by-week schedule tailored to your schedule."
    },
    {
      q: "Can I edit or delete study plans once they are generated?",
      a: "Yes! Any study plans generated by you are stored securely in your dashboard. You can view their full breakdown, delete them from your catalogue, or create manual schedules."
    },
    {
      q: "Is Google Authentication supported?",
      a: "Yes. StudyForge AI supports full Firebase Authentication, enabling you to sign up with standard email keys or single-click Google Login credentials."
    },
    {
      q: "Which AI model powers the Study Buddy chatbot?",
      a: "The conversational Chat Assistant and Study Planner utilize Google Gemini (gemini-1.5-flash) for low-latency response generation and robust structural formatting."
    }
  ];

  return (
    <div className="space-y-16 pb-16">
      {/* 1. Hero Section */}
      <header className="relative min-h-[65vh] flex items-center justify-center overflow-hidden px-4">
        {/* Glow Spheres */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-brand-primary/10 rounded-full blur-[120px] pointer-events-none"></div>
        <div className="absolute bottom-10 right-10 w-[300px] h-[300px] bg-brand-secondary/10 rounded-full blur-[90px] pointer-events-none"></div>

        <div className="max-w-4xl text-center space-y-8 z-10">
          <div className="inline-flex items-center space-x-2 bg-slate-900/80 border border-slate-800 px-4 py-1.5 rounded-full text-xs font-semibold text-brand-secondary">
            <Sparkles className="w-4.5 h-4.5 animate-spin" />
            <span>Next-Generation Study Assistant Launched</span>
          </div>

          <h1 className="text-4xl sm:text-6xl font-extrabold text-white tracking-tight leading-tight">
            Forge Your Academic Path with <br />
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-brand-primary via-brand-secondary to-brand-accent">
              Agentic AI Assistance
            </span>
          </h1>

          <p className="text-lg text-slate-300 max-w-2xl mx-auto">
            Design hyper-customized weekly syllabi, interact with a dedicated chatbot mentor, and analyze your educational routines instantly on a clean dashboard.
          </p>

          {/* Floating Hero Stats Chips */}
          <div className="flex flex-wrap justify-center items-center gap-4 text-xs sm:text-sm text-slate-400 font-semibold pt-1">
            <div className="flex items-center gap-2 bg-slate-900/60 border border-slate-800 px-3.5 py-1.5 rounded-full"><Users className="w-4 h-4 text-brand-primary" /> 10K+ Students</div>
            <div className="flex items-center gap-2 bg-slate-900/60 border border-slate-800 px-3.5 py-1.5 rounded-full"><Sparkles className="w-4 h-4 text-brand-secondary" /> 12K+ Plans Generated</div>
            <div className="flex items-center gap-2 bg-slate-900/60 border border-slate-800 px-3.5 py-1.5 rounded-full"><TrendingUp className="w-4 h-4 text-brand-accent" /> 98% Success Rate</div>
          </div>

          <div className="flex flex-col sm:flex-row justify-center items-center gap-4 pt-2">
            <Link 
              to="/items/add" 
              className="w-full sm:w-auto px-8 py-3.5 bg-brand-primary hover:bg-brand-primary/95 text-white font-semibold rounded-xl shadow-lg shadow-brand-primary/30 transform hover:-translate-y-0.5 transition-all text-center flex items-center justify-center space-x-2"
            >
              <Sparkles className="w-5 h-5" />
              <span>Generate Study Plan</span>
            </Link>
            <Link 
              to="/explore" 
              className="w-full sm:w-auto px-8 py-3.5 bg-slate-900 border border-slate-800 hover:bg-slate-850 text-slate-200 font-semibold rounded-xl transition-all text-center flex items-center justify-center space-x-2"
            >
              <Compass className="w-5 h-5 text-brand-accent" />
              <span>Explore Plans</span>
            </Link>
            <Link 
              to="/chat" 
              className="w-full sm:w-auto px-8 py-3.5 bg-slate-900 border border-slate-850 hover:border-brand-secondary/40 text-slate-200 hover:text-white font-semibold rounded-xl transition-all text-center flex items-center justify-center space-x-2"
            >
              <MessageCircle className="w-5 h-5 text-brand-secondary" />
              <span>Try AI Buddy</span>
            </Link>
          </div>
        </div>
      </header>

      {/* 2. Features Grid */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-white mb-4">Empowering Modern Learning</h2>
          <p className="text-slate-400">Everything you need to plan, track, and master your educational interests in a single canvas.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="glass-card p-8 space-y-4 hover:border-brand-primary/40 transition-colors">
            <div className="h-12 w-12 bg-brand-primary/20 border border-brand-primary/30 rounded-xl flex items-center justify-center text-brand-primary">
              <Sparkles className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">AI Syllabus Planner</h3>
            <p className="text-sm text-slate-400">
              Input a subject name and study constraints to receive a detailed week-by-week study structure mapping out topics and resource links.
            </p>
          </div>

          <div className="glass-card p-8 space-y-4 hover:border-brand-secondary/40 transition-colors">
            <div className="h-12 w-12 bg-brand-secondary/20 border border-brand-secondary/30 rounded-xl flex items-center justify-center text-brand-secondary">
              <MessageCircle className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">Study Buddy Chat</h3>
            <p className="text-sm text-slate-400">
              Stuck on a problem or need revision chips? Ask our companion chatbot, which stores context-aware memory to personalize study recommendations.
            </p>
          </div>

          <div className="glass-card p-8 space-y-4 hover:border-brand-accent/40 transition-colors">
            <div className="h-12 w-12 bg-brand-accent/20 border border-brand-accent/30 rounded-xl flex items-center justify-center text-brand-accent">
              <TrendingUp className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">Analytics Dashboard</h3>
            <p className="text-sm text-slate-400">
              Track subject breakdowns, study hours distributions, and completion levels in interactive charts powered by Recharts modules.
            </p>
          </div>
        </div>
      </section>

      {/* 3. Statistics Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 bg-slate-950/40 py-12 rounded-3xl border border-slate-900">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          <div className="space-y-2">
            <div className="text-4xl font-extrabold text-brand-primary">2,500+</div>
            <div className="text-sm text-slate-400 font-medium">Students Enrolled</div>
          </div>
          <div className="space-y-2">
            <div className="text-4xl font-extrabold text-brand-secondary">12,800+</div>
            <div className="text-sm text-slate-400 font-medium">Plans Generated</div>
          </div>
          <div className="space-y-2">
            <div className="text-4xl font-extrabold text-brand-accent">98.4%</div>
            <div className="text-sm text-slate-400 font-medium">Completion Rate</div>
          </div>
          <div className="space-y-2">
            <div className="text-4xl font-extrabold text-white">4.9/5</div>
            <div className="text-sm text-slate-400 font-medium">Satisfaction Score</div>
          </div>
        </div>
      </section>

      {/* 4. How It Works */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-white mb-4">4 Steps to Succeed</h2>
          <p className="text-slate-400">A clear, simple method to design your customized learning routines.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative">
          <div className="absolute top-1/2 left-0 right-0 h-0.5 bg-slate-800 -translate-y-1/2 hidden md:block z-0"></div>

          <div className="glass-card p-6 text-center space-y-4 relative z-10 bg-slate-900">
            <div className="w-10 h-10 bg-brand-primary text-white rounded-full flex items-center justify-center font-bold mx-auto">1</div>
            <h4 className="text-md font-bold text-white">Create Account</h4>
            <p className="text-xs text-slate-400">Register in seconds with email or single-click Google Sign-in.</p>
          </div>

          <div className="glass-card p-6 text-center space-y-4 relative z-10 bg-slate-900">
            <div className="w-10 h-10 bg-brand-secondary text-white rounded-full flex items-center justify-center font-bold mx-auto">2</div>
            <h4 className="text-md font-bold text-white">Enter Parameters</h4>
            <p className="text-xs text-slate-400">Define your subject, difficulty grade, and available daily hours.</p>
          </div>

          <div className="glass-card p-6 text-center space-y-4 relative z-10 bg-slate-900">
            <div className="w-10 h-10 bg-brand-accent text-white rounded-full flex items-center justify-center font-bold mx-auto">3</div>
            <h4 className="text-md font-bold text-white">AI Synthesizes</h4>
            <p className="text-xs text-slate-400">Gemini compiles a comprehensive week-by-week schedule details.</p>
          </div>

          <div className="glass-card p-6 text-center space-y-4 relative z-10 bg-slate-900">
            <div className="w-10 h-10 bg-slate-700 text-white rounded-full flex items-center justify-center font-bold mx-auto">4</div>
            <h4 className="text-md font-bold text-white">Track Progress</h4>
            <p className="text-xs text-slate-400">Examine details, track stats on dashboard, and chat with AI buddy.</p>
          </div>
        </div>
      </section>

      {/* 5. Popular Study Plans (Seeded Cards) */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between mb-12">
          <div>
            <h2 className="text-3xl font-bold text-white">Popular Study Blueprints</h2>
            <p className="text-slate-400 text-sm mt-1">Direct access to high-quality curated study paths.</p>
          </div>
          <Link to="/explore" className="text-sm font-semibold text-brand-primary hover:text-brand-primary/80 transition-colors">
            View All Plans →
          </Link>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
            {Array.from({ length: 4 }).map((_, i) => <CardSkeleton key={i} />)}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
            {plans.map(plan => (
              <PlanCard key={plan._id} plan={plan} />
            ))}
          </div>
        )}

        {seeding && (
          <div className="mt-4 text-center text-xs text-brand-secondary animate-pulse">
            Seeding fresh sandbox study blueprints... Please wait.
          </div>
        )}
      </section>

      {/* 6. Testimonials */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-white mb-4">Reviews from Learners</h2>
          <p className="text-slate-400">See how students are using StudyForge AI to optimize their study hours.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="glass-card p-6 space-y-4">
            <p className="text-sm text-slate-350 italic">
              "The AI Planner generated a React developer course schedule in 5 seconds. The weekly breakdown helps me stay focused without worrying about searching for materials."
            </p>
            <div className="flex items-center space-x-3">
              <img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&h=80" alt="Sarah" className="w-10 h-10 rounded-full object-cover" />
              <div>
                <h5 className="text-sm font-bold text-white">Sarah Jenkins</h5>
                <span className="text-xs text-slate-500">Computer Science Student</span>
              </div>
            </div>
          </div>

          <div className="glass-card p-6 space-y-4">
            <p className="text-sm text-slate-350 italic">
              "Using the Study Buddy chat tool while learning algorithms feels like pair programming with an experienced teacher. Spaced repetition features are outstanding."
            </p>
            <div className="flex items-center space-x-3">
              <img src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&h=80" alt="David" className="w-10 h-10 rounded-full object-cover" />
              <div>
                <h5 className="text-sm font-bold text-white">David K.</h5>
                <span className="text-xs text-slate-500">Self-Taught Engineer</span>
              </div>
            </div>
          </div>

          <div className="glass-card p-6 space-y-4">
            <p className="text-sm text-slate-350 italic">
              "The dashboard analytics represent a game changer. Visualizing my study hours versus subject completion motivated me to finish my Calculus syllabus on time."
            </p>
            <div className="flex items-center space-x-3">
              <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&h=80" alt="Elena" className="w-10 h-10 rounded-full object-cover" />
              <div>
                <h5 className="text-sm font-bold text-white">Elena Rostova</h5>
                <span className="text-xs text-slate-500">Math Olympiad Trainee</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 7. FAQ Section */}
      <section className="max-w-3xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-12">
          <HelpCircle className="w-10 h-10 text-brand-primary mx-auto mb-3" />
          <h2 className="text-3xl font-bold text-white">Frequently Asked Questions</h2>
        </div>

        <div className="space-y-4">
          {faqData.map((faq, idx) => (
            <div key={idx} className="glass-card overflow-hidden">
              <button 
                onClick={() => toggleFaq(idx)}
                className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-slate-900 transition-colors"
              >
                <span className="font-semibold text-white text-sm sm:text-base">{faq.q}</span>
                <ChevronDown className={`w-5 h-5 text-slate-400 transition-transform duration-200 ${activeFaq === idx ? 'rotate-180' : ''}`} />
              </button>
              {activeFaq === idx && (
                <div className="px-6 pb-5 pt-1 text-sm text-slate-400 leading-relaxed border-t border-slate-900 bg-slate-950/20">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 8. Newsletter Subscription */}
      <section className="max-w-4xl mx-auto px-4">
        <div className="glass-card p-10 text-center relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900">
          <div className="absolute -top-24 -left-24 w-48 h-48 bg-brand-primary/5 rounded-full blur-2xl"></div>
          
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white mb-3">Keep Learning and Improving</h2>
          <p className="text-slate-400 text-sm max-w-lg mx-auto mb-8">
            Subscribe to our weekly newsletter to receive custom study tips, curated resources, and notifications when new AI learning capabilities launch.
          </p>

          {newsletterSubscribed ? (
            <div className="bg-brand-accent/10 border border-brand-accent/20 rounded-xl py-4 px-6 text-brand-accent inline-block text-sm font-semibold animate-pulse">
              🎉 Thank you for subscribing! Check your inbox soon.
            </div>
          ) : (
            <form onSubmit={handleSubscribe} className="flex flex-col sm:flex-row items-center justify-center gap-3 max-w-md mx-auto">
              <input 
                type="email" 
                required
                placeholder="Enter your email address"
                value={newsletterEmail}
                onChange={(e) => setNewsletterEmail(e.target.value)}
                className="w-full px-4 py-3 bg-slate-900 border border-slate-800 rounded-xl text-white text-sm focus:outline-none focus:border-brand-primary transition-colors"
              />
              <button 
                type="submit"
                className="w-full sm:w-auto px-6 py-3 bg-brand-primary hover:bg-brand-primary/90 text-white text-sm font-semibold rounded-xl flex items-center justify-center space-x-2 shrink-0 transition-colors"
              >
                <Send className="w-4 h-4" />
                <span>Subscribe</span>
              </button>
            </form>
          )}
        </div>
      </section>
    </div>
  );
};
